config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :admin do
    resources :products
  end
  resources :products, only: [:index, :show]
  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    validates_presence_of :name, :price, :quantity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    class AuthorizationError < StandardError; end
    layout 'admin'
    before_action :authorize_admin!

    rescue_from AuthorizationError do
      flash[:error] = e.message
      redirect_to root_path
    end

    private

    def authorize_admin!
      return if current_user.present? && current_user.admin

      raise AuthorizationError, 'You are not permitted to access this page or it does not exist'
    end
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::BaseController
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    # GET /products
    def index
      @products = Product.all
    end

    # GET /products/1
    def show
    end

    # GET /products/new
    def new
      @product = Product.new
    end

    # GET /products/1/edit
    def edit
    end

    # POST /products
    def create
      @product = Product.new(product_params)

      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /products/1
    def update
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /products/1
    def destroy
      @product.destroy
      respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :quantity, :price)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :authenticate_user!
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_field :name %>
  <%= form.number_field :quantity %>
  <%= form.number_field :price %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/admin/products/index.html.erb
<section class="hero is-danger is-small">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Products
      </p>
      <p class="subtitle">
        Here is what we offer
      </p>
    </div>
  </div>
</section>
<div class="box cta">
  <p class="has-text-centered">
    Click on on selected product to see more details
  </p>
</div>
<section class="container">
  <% @products.each_slice(3) do |batch| %>
    <div class="columns features">
    <% batch.each do |product| %>
      <div class="column is-4">
        <div class="card is-shady">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="https://fuzati.com/wp-content/uploads/2016/12/Ruby-Logo.png" alt="Placeholder image" class="modal-button" data-target="modal-image2">
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <h5><%= product.name %></h5>
              <h6><%= product.price %></h6>
              <div>
                In stock: <span class="is-size-6 has-text-weight-semibold	"><%= product.quantity %></span>
              </div>
              <span class="button is-link">
                <%= link_to(product) do %>
                  <span class="has-text-white is-size-6 has-text-weight-semibold">Details</span>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</section>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop Admin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
    <% if flash[:notice] %>
      <div class="notification is-success""><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-warning"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:error] %>
     <div class="notification is-danger"><%= flash[:error] %></div>
    <% end %>
  <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class="notification is-success""><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-warning"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="notification is-danger"><%= flash[:error] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<section class="hero is-danger is-small">
  <div class="hero-body">
    <div class="container has-text-centered">
      <p class="title">
        Products
      </p>
      <p class="subtitle">
        Here is what we offer
      </p>
    </div>
  </div>
</section>
<div class="box cta">
  <p class="has-text-centered">
    Click on on selected product to see more details
  </p>
</div>
<section class="container">
  <% @products.each_slice(3) do |batch| %>
    <div class="columns features">
    <% batch.each do |product| %>
      <div class="column is-4">
        <div class="card is-shady">
          <div class="card-image">
            <figure class="image is-4by3">
              <img src="https://fuzati.com/wp-content/uploads/2016/12/Ruby-Logo.png" alt="Placeholder image" class="modal-button" data-target="modal-image2">
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <h5><%= product.name %></h5>
              <h6><%= product.price %></h6>
              <div>
                In stock: <span class="is-size-6 has-text-weight-semibold	"><%= product.quantity %></span>
              </div>
              <span class="button is-link">
                <%= link_to(product) do %>
                  <span class="has-text-white is-size-6 has-text-weight-semibold">Details</span>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</section>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', products_path %>